language: generic
sudo: required
services:
  - docker

before_install: 
  - docker build -t badi1298/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true badi1298/docker-react npm test
